// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAarxxnJStEM_l7r_UE0MPIG5FHgE9GOc',
    appId: '1:999430020271:web:5bb03e2949a093991dc85a',
    messagingSenderId: '999430020271',
    projectId: 'dessert-delivery-dash',
    authDomain: 'dessert-delivery-dash.firebaseapp.com',
    storageBucket: 'dessert-delivery-dash.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKh4lUtqQUvjhbSqsntK7k0YbAOnGY6KA',
    appId: '1:999430020271:android:b0105748f85da30f1dc85a',
    messagingSenderId: '999430020271',
    projectId: 'dessert-delivery-dash',
    storageBucket: 'dessert-delivery-dash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbAv8WFXeZSHQz12QdxqmitVwWLlHxsu4',
    appId: '1:999430020271:ios:f72bd636a35903761dc85a',
    messagingSenderId: '999430020271',
    projectId: 'dessert-delivery-dash',
    storageBucket: 'dessert-delivery-dash.firebasestorage.app',
    iosBundleId: 'com.example.dessertDeliveryDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbAv8WFXeZSHQz12QdxqmitVwWLlHxsu4',
    appId: '1:999430020271:ios:f72bd636a35903761dc85a',
    messagingSenderId: '999430020271',
    projectId: 'dessert-delivery-dash',
    storageBucket: 'dessert-delivery-dash.firebasestorage.app',
    iosBundleId: 'com.example.dessertDeliveryDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAarxxnJStEM_l7r_UE0MPIG5FHgE9GOc',
    appId: '1:999430020271:web:2ef75e1e07a89c6a1dc85a',
    messagingSenderId: '999430020271',
    projectId: 'dessert-delivery-dash',
    authDomain: 'dessert-delivery-dash.firebaseapp.com',
    storageBucket: 'dessert-delivery-dash.firebasestorage.app',
  );
}
